blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: https://github.com/DataDog/flask-realworld-example-app/security/policy
    about: Please report security vulnerabilities privately
  - name: Datadog Support
    url: https://www.datadoghq.com/support/
    about: Get help from Datadog support team
  - name: Documentation
    url: https://docs.datadoghq.com/
    about: Browse Datadog documentation
